package com.example.comicslibrary

import dagger.hilt.android.HiltAndroidApp

//aparaithto gia na mporei na kanei to Hilt automatically generate code at runtime
//px an eixame mia klassh me polles paramterous(opvw o PodcastDetailsVC), auto
//ta kanei automata autogenerated ayta ta constructor dependencies
@HiltAndroidApp
class ComicsApplication {
}